### ISSUE TITLE
Unable to download extension

### ISSUE THREAD

**Issue by twolfson** [jiripospisil/chrome-ext-downloader#1]
I was interested in downloading the icomoon extension via this module. However, it seems to not be downloading the file:

https://chrome.google.com/webstore/detail/icomoon/kppingdhhalimbaehfmhldppemnmlcjd?hl=en

``` bash
$ ced kppingdhhalimbaehfmhldppemnmlcjd
Unable to download the CRX file.
```

The site http://chrome-extension-downloader.com/ seems to be able to download the extension fine.

**Comment by jiripospisil** [comment]
@twolfson Thank you for the bug report. It should be working now.

**Comment by twolfson** [comment]
Yep, looks good now :+1:
