### ISSUE TITLE
Unable to download the CRX file

### ISSUE THREAD

**Issue by stewartlord** [jiripospisil/chrome-ext-downloader#2]
The `finalURL` is not composed correctly on Mac. Maybe `util.format()` behaves differently on Mac, but the result is definitely not what you want. I suspect it has to do with the % encoded characters. Simple string concatenation works

**Comment by jiripospisil** [comment]
Huh, could you post the URL of the extension?

**Comment by stewartlord** [comment]
Sure!
`https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen`
This worked fine on Linux, but on Mac the URL was mangled.

**Comment by jiripospisil** [comment]
I don't think it has anything to do with the platform but rather the Node.js version. I can download the extension just fine with Node.js 7.9 but it indeed fails with 8.1.2. What version are you running? Nevertheless, I will look into it more over the weekend.

**Comment by stewartlord** [comment]
That makes sense. I am running 8.1.0 (on my mac). Thanks!

**Comment by jiripospisil** [comment]
It works again with Node.js 8.1.3. I *think* it was fixed by https://github.com/nodejs/node/pull/13674. Thank you for the bug report!

**Comment by stewartlord** [comment]
Thanks for following-up @jiripospisil :+1:
