### ISSUE TITLE
Chrome extension download URL changed: Unable to download the CRX file

### ISSUE THREAD

**Issue by Archinowsk** [jiripospisil/chrome-ext-downloader#5]
Seems like the Chrome extension download URL has been changed and `ced` does not work at the moment. New query parameter is required: `acceptformat=crx2,crx3`.

Here is some discussion: https://stackoverflow.com/questions/7184793/how-to-download-a-crx-file-from-the-chrome-web-store-for-a-given-id/14099762#14099762

Current `ced` generated URL which does not work:

```
https://clients2.google.com/service/update2/crx?response=redirect&prodversion=38.0&x=id%3Dlmhkpmbekcpmknklioeibfkpmmfibljd%26installsource%3Dondemand%26uc
```

Working URL with `acceptformat=crx2,crx3`:

```
https://clients2.google.com/service/update2/crx?response=redirect&prodversion=38.0&acceptformat=crx2,crx3&x=id%3Dlmhkpmbekcpmknklioeibfkpmmfibljd%26uc
```

**Comment by Archinowsk** [comment]
Seems like there is also an issue with extracting the downloaded `crx` file because the format has changed: https://gromnitsky.blogspot.com/2019/04/crx3.html.

**Comment by LeoYawoo** [comment]
mark

**Comment by jiripospisil** [comment]
Hello, I don't plan on working on this project anymore. Please use https://robwu.nl/crxviewer (https://github.com/Rob--W/crxviewer) instead. Thank you.
